# Generated by Django 3.2.8 on 2021-10-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=18)),
                ('Password', models.CharField(max_length=18)),
                ('Wins', models.IntegerField()),
            ],
        ),
    ]
