# Generated by Django 3.2.8 on 2021-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_online',
            field=models.BooleanField(default=False),
        ),
    ]
