# Generated by Django 3.2.8 on 2021-10-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('Game_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Player_one', models.IntegerField(default=-1)),
                ('Player_two', models.IntegerField(default=-1)),
            ],
        ),
    ]
