# Generated by Django 3.2.8 on 2021-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('opening_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sequence_of_moves', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=18)),
            ],
        ),
    ]
