# Generated by Django 3.2.8 on 2021-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='Description',
            field=models.CharField(max_length=300),
        ),
    ]
